use worker::*;

// Embed scripts
static BOOTSTRAP_SH: &str = include_str!("../../bootstrap.sh");
static INSTALL_SH: &str = include_str!("../../install.sh");

// Include file generated by Bash script
include!("generated_files.rs");

#[event(fetch)]
pub async fn main(req: Request, _env: Env, _ctx: worker::Context) -> Result<Response> {
    let url = req.url()?;
    let headers = req.headers();

    let host_from_header = headers
        .get("host")?
        .map(|h| h.trim().to_string())
        .filter(|h| !h.is_empty());

    let host = host_from_header
        .or_else(|| url.host_str().map(|h| h.to_string()))
        .unwrap_or_default();

    let scheme = url.scheme();
    let mut base_url = if host.is_empty() {
        "__DOTFILES_BASE_URL__".to_string()
    } else {
        format!("{}://{}", scheme, host)
    };

    if let Some(port) = url.port() {
        base_url = format!("{}:{}", base_url, port);
    }

    let path_buf = url.path().to_string();
    let path = path_buf.trim_start_matches('/');

    // bootstrap script (root)
    if path.is_empty() {
        let bootstrap = BOOTSTRAP_SH.replace("__DOTFILES_BASE_URL__", &base_url);
        let mut resp = Response::ok(bootstrap)?;
        resp.headers_mut()
            .set("Content-Type", "text/plain; charset=utf-8")?;
        return Ok(resp);
    }

    if path == "raw/install.sh" {
        let mut resp = Response::ok(INSTALL_SH)?;
        resp.headers_mut()
            .set("Content-Type", "text/plain; charset=utf-8")?;
        return Ok(resp);
    }

    // Screenshots lookup (auto-generated by script - O(1) match)
    match get_file(path) {
        Some((bytes, mime_type)) => {
            let mut resp = Response::from_bytes(bytes.to_vec())?;
            resp.headers_mut().set("Content-Type", mime_type)?;
            Ok(resp)
        }
        None => Response::error("Not Found", 404),
    }
}
