[general]
engines-order=['xkb:us::eng', 'Bamboo::Us']
preload-engines=['xkb:us::eng', 'Bamboo::Us']
use-global-engine=true
use-system-keyboard-layout=true
version='1.5.34'

[general/hotkey]
triggers=['<Alt>space']

[panel]
show-icon-on-systray=true

[panel/emoji]
favorites=['♣️']
