#!/bin/sh

DIR="$HOME/.config/"

rofi \
	-show drun \
	-modi run,drun,ssh,window \
	-scroll-method 0 \
	-drun-display-format "{name}" \
	-terminal alacritty \
	-kb-cancel Escape\
	-theme "$DIR"/rofi/themes/launcher.rasi \
	-config "$DIR"/rofi/config.rasi &
