#!/bin/sh

DIR="$HOME/.config"
rofi_cmd="rofi -theme $DIR/rofi/themes/powermenu.rasi"
uptime=$(uptime -p | sed -e 's/up //g')

handle_choice() {
    ans=$(rofi -dmenu -i -no-fixed-num-lines -p "Are You Sure? (y/n) : " -theme "$DIR/rofi/themes/confirm.rasi")
    case "$ans" in
        y) eval "$1" || rofi -e "Failed to execute $1";;
        n) exit 0;;
        *) exit 0;;
    esac
}

# Options
shutdown=""
reboot=""
hibernate="󰒲"
lock=""
suspend="󰤄"
logout="󰍃"

# Variable passed to rofi
options="$shutdown\n$reboot\n$hibernate\n$lock\n$suspend\n$logout"

chosen="$(printf "%b" "$options" | $rofi_cmd -p "UP - $uptime" -dmenu -selected-row 2)"
case $chosen in
    "$shutdown")
        handle_choice "systemctl poweroff"
        ;;
    "$reboot")
        handle_choice "systemctl reboot"
        ;;
    "$hibernate")
        handle_choice "systemctl hibernate"
        ;;
    "$lock")
        lock
        ;;
    "$suspend")
        handle_choice "systemctl suspend"
        ;;
    "$logout")
        handle_choice "i3-msg exit"
        ;;
    *)
        exit 0
        ;;
esac

exit 0
