#!/usr/bin/env bash
set -euo pipefail

# Screenshots directory
SCREENSHOTS_DIR="../screenshots"

# Dist directory for bundled assets
DIST_DIR="../dist"
TARBALL_NAME="dotfiles.tar.gz"
TARBALL_PATH="$DIST_DIR/$TARBALL_NAME"

# Rust file to generate
OUT_FILE="src/generated_files.rs"

echo "// Auto-generated by generate-files.sh" > "$OUT_FILE"
echo "// Do not edit manually" >> "$OUT_FILE"
echo "" >> "$OUT_FILE"

# Array to store mappings for match expression
MATCH_ENTRIES=()

shopt -s nullglob

# Ensure dist dir exists
mkdir -p "$DIST_DIR"

# Create tarball without using git clone later
TAR_EXCLUDES=(
    "--exclude=./.git"
    "--exclude=./.gitignore"
    "--exclude=./.github"
    "--exclude=./worker"
    "--exclude=./dist"
    "--exclude=./node_modules"
    "--exclude=./target"
    "--exclude=./screenshots"
)

tar -czf "$TARBALL_PATH" "${TAR_EXCLUDES[@]}" -C .. .

# Sort files to ensure consistent output
FILES=("$SCREENSHOTS_DIR"/*)
if (( ${#FILES[@]} )); then
    IFS=$'\n' read -r -d '' -a FILES < <(printf '%s\n' "${FILES[@]}" | sort && printf '\0')
fi
for f in "${FILES[@]}"; do
    if [[ -f "$f" ]]; then
        # Get filename and create Rust variable
        filename=$(basename "$f")
        varname=$(echo "$filename" | tr '.-' '__' | tr '[:lower:]' '[:upper:]')

        # Determine MIME type from extension
        ext="${filename##*.}"
        case "$ext" in
            png) mime="image/png" ;;
            jpg|jpeg) mime="image/jpeg" ;;
            gif) mime="image/gif" ;;
            svg) mime="image/svg+xml" ;;
            webp) mime="image/webp" ;;
            *) mime="application/octet-stream" ;;
        esac

        # Write include_bytes! to Rust file
        echo "pub static $varname: &[u8] = include_bytes!(\"../$f\");" >> "$OUT_FILE"

        # Save to array for match expression
        MATCH_ENTRIES+=("(\"$filename\", $varname, \"$mime\")")
    fi
done

# Include tarball as static bytes
echo "pub static DOTFILES_TAR_GZ: &[u8] = include_bytes!(\"../../dist/$TARBALL_NAME\");" >> "$OUT_FILE"
MATCH_ENTRIES+=("(\"$TARBALL_NAME\", DOTFILES_TAR_GZ, \"application/gzip\")")

echo "" >> "$OUT_FILE"
echo "// Auto-generated match function for fast lookup" >> "$OUT_FILE"
echo "pub fn get_file(path: &str) -> Option<(&[u8], &str)> {" >> "$OUT_FILE"
echo "    match path {" >> "$OUT_FILE"
for entry in "${MATCH_ENTRIES[@]}"; do
    # Parse entry: ("filename", VARNAME, "mime")
    IFS=',' read -r filename_part varname_part mime_part <<< "$entry"
    filename=$(echo "$filename_part" | sed -E 's/^\("([^"]+)".*/\1/')
    varname=$(echo "$varname_part" | sed -E 's/^ *([^, ]+).*/\1/')
    mime=$(echo "$mime_part" | sed -E 's/^ *"([^"]+)"\).*/\1/')
    echo "        \"$filename\" => Some(($varname, \"$mime\"))," >> "$OUT_FILE"
done
echo "        _ => None," >> "$OUT_FILE"
echo "    }" >> "$OUT_FILE"
echo "}" >> "$OUT_FILE"

echo "Generated Rust file: $OUT_FILE"

shopt -u nullglob
