;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[glyph]
gleft = ""
gright = ""

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/sep]
type = custom/text
format = " "

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; ------------- left ----------------
[module/left]
type = custom/text
format-foreground = ${colors.bg1}
format = ${glyph.gleft}
format-padding = 0
format-font = 4

;; ------------ right --------------
[module/right]
type = custom/text
format-foreground = ${colors.bg1}
format = ${glyph.gright}
format-padding = 0
format-font = 4

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/sepl]
type = custom/text
format = " | "
format-foreground = ${colors.bg2}
format-background = ${colors.bg1}

[module/sepr]
type = custom/text
format = "  "
format-foreground = ${colors.blue}
format-background = ${colors.bg}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/random]
type = custom/text

format = " "
format-font = 6
format-background = ${colors.bg}
format-foreground = ${colors.gray}
format-padding = 0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
